### ISSUE TITLE
This doesn't seem to work

### ISSUE THREAD

**Issue by Frederik-Baetens** [renxida/labtunnel#4]
I have my host defined as: 

```
Host myhost
    HostName myhost.com
    Port     22
    User     myuser
    IdentityFile ~/.ssh/id_ed25519
    LocalForward 22222 localhost:22
```

and even running the command ssh -NT -o ServerAliveInterval=60 -o ExitOnForwardFailure=yes myhost

does not work

**Comment by renxida** [comment]
Hi Frederik,

This is an issue with SSH, but I will attempt to help you anyways.

Try directly using the command `ssh -NTL 2222:localhost:22 myuser@myhost.com
-i ~/.ssh/id_ed25519` to connect. If it doesn't work, it is likely a
problem with your host or your identity file.

Otherwise, it might be an issue with the location/format/permissions of
your host config file.

Keep in touch,
Xida Ren

**Comment by Frederik-Baetens** [comment]
Hmm, i think the issue was that my rpi was hanging on gssapi-with-mic, because i was sshing from a raspberry pi zero, which didn't have enough entropy. After testing a bit it did seem to work 10 minutes after boot, but that was with a modified config & service, i will test again with your original service, and report back tomorrow.

**Comment by renxida** [comment]
GL, HF. I'm rooting for you and waiting for your success.

**Comment by Frederik-Baetens** [comment]
I think for my use case i needed RemoteForward instead of LocalForward.

My use case is: i have a rpi behind a natted network, and want to ssh to it from outside the network. I also have a server with a public ip.

With RemoteForward instead of LocalForward i can ssh into my server, and then ssh to localhost -p 22222 for the raspberry pi.

The entropy thing was also an issue, but changing both of these things fixed my issue.

**Comment by renxida** [comment]
It seems that you have solved the mystery. Congratulations. Best of luck in
your future endeavors.
